version: '2'
services:
  gogs:
    image: casept/gogs:armhf
    ports:
      #Web interface
      - "3000:3000"
      #SSH port
      - "2222:2222"
    build: ../../build/gogs
    volumes:
      #Mount the custom config
      - ./app.ini:/opt/gogs/custom/conf/app.ini
      - gogs-misc:/home/gogs/data
      - gogs-repos:/home/gogs/repositories
      - gogs-logs:/home/gogs/logs
      - gogs-ssh:/home/gogs/.ssh
    restart: always


volumes:
  gogs-misc:
    external: false
  gogs-repos:
    external: false
  gogs-logs:
    external: false
  gogs-ssh:
    external: false
