version: '2'
services:
  jackett-private:
    image: casept/jackett-private:amd64
    ports:
      - "9117:9117"
    build: ../../build/jackett-private
    volumes:
      - jackett-private:/home/jackett
    restart: always

    environment:
      #Limit the amount of memory mono allocates to jackett
      MONO_GC_PARAMS: max-heap-size=64m


  jackett-public:
    image: casept/jackett-public:amd64
    ports:
      - "9118:9117"
    build: ../../build/jackett-public
    volumes:
      - jackett-public:/home/jackett
    restart: always

    environment:
      #Limit the amount of memory mono allocates to jackett
      MONO_GC_PARAMS: max-heap-size=64m

volumes:
  jackett-private:
    external: false
  jackett-public:
    external: false
